supertime/profil/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name = 'profil'

urlpatterns=[
    path('',views.first_time_user,name='register'),
    path('index/',views.index, name='index'),
    path('dashboad/',views.dashboard,name='dashboad'),
    path('add/poste/', views.add_poste , name='save_poste'),
    path('add/personnel/', views.add_personnel, name='save_employe'),
    # path('details/', views.detail_register, name='details_user'),
    path('personnel/list/', views.personnel_list , name='liste_employe'),
    # path('Ajout horaire/', views.part3, name='part3'),
    path('attendance/',views.attendance,name='attendance'),
    path('dowloands/log/lecteur?<int:lecteur_id>/',views.get_log_data,name='get_log_data'),
    path('dowloands/user/lecteur?<int:lecteur_id>/',views.add_users,name='add_users'),
    path('user/list/',views.user_list,name="liste_user"),
    path('logs/data/',views.raw_data,name='logs'),
    path('get_somme_for_poste/', views.get_somme_for_poste, name='get_somme_for_poste'),
    path('get_start/', views.get_start, name='get_start'),
    path('get_end/', views.get_end, name='get_end'),
    path('get_time_work/', views.get_time_work, name='get_time_work'),
    path('get_tolerance_time/', views.get_tolerance_time, name = 'get_tolerance_time'),
    path('dowloands/attendance/', views.get_attendance_data, name = 'add_horaire'),
    path('historique/',views.historique,name='historique'),
    path('add/lecteur/',views.add_drive, name='add_drive'),
    path('help/',views.help,name='help'),
    path('edit/poste/<int:poste_id>/', views.edit_poste, name='modife_poste'),
    path('edit/personnel/personnel?<int:personnel_id>/',views.edit_personnel,name='modife_employe'),
    path('edit/attendances/attendance?<int:Horaire_id>/',views.edit_attendance,name='modife_attendance'),
    path('profil/employe?<int:Personnel_id>/',views.personnel_profil,name='profil_employe'),
    path('delete-employe/employé?<int:Personnel_id>/',views.delete_personnel,name='delete_personnel'),
    path('delete-poste/poste?<int:Poste_id>/',views.delete_poste,name='delete_poste'),
    path('ternimal/list/', views.terminal_list, name = 'liste_drive'),
    path('profil/user/',views.user_profil, name = 'profil_user'),
    path('poste/', views.poste_list, name='liste_poste'),
    path('Fiche/<int:Personnel_id>/', views.personnel_salary, name='salary'),
    path('delete-lecteur/id=<int:lecteur_id>/',views.delete_drive,name='delete_drive'),
    path('edit/lecteur/id=<int:lecteur_id>/',views.edit_drive,name='modife_drive'),
    path('delete-employe/',views.delete_employees,name='delete_employees'),
    path('dowloands/log-alls/',views.get_all_log_data,name='get_all_log_data'),
      
]

supertime/profil/templates/profil/add_drive.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <link rel="stylesheet" href="{%static 'profil/css/index.css'%}"> -->
    <link rel="stylesheet" href="{% static 'profil/boxicons-2.1.4/css/boxicons.min.css' %}" />
    <link rel="stylesheet" href="{% static 'profil/css/sidebar.css' %}">
    <link rel="stylesheet" href="{% static 'profil/css/machine.css' %}">
    <link rel="stylesheet" href="{% static 'profil/css/footer.css'%}">
</head>
    <body>

        {% include 'profil/couche/sidebar.html' %}

        <section class="home-section form">
            <div class="home-content">
                <i class="bx bx-menu"></i>
                <span class="text">Terminal</span>
            </div>
            <main class="wrapper">
                <div class="form signup">
                    <header>CONNECTER UN TERMINAL 
                        </header>
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <p>{{message}}</p>
                        <input type="submit" id="loginBtn" value="Se connecter" />
                    </form>
                </div>
            </main>
        </section>
        {% include 'profil/couche/footer.html' %}
    <script src="{% static 'profil/js/sidebar.js' %}"></script>
</body>
</html>

supertime/profil/templates/profil/liste_drive.html
{% load static %}

<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Liste des terminaux</title>
    <link rel="stylesheet" href="{% static 'profil/boxicons-2.1.4/css/boxicons.min.css' %}" />
    <link rel="stylesheet" href="{% static 'profil/css/sidebar.css' %}">
    <link rel="stylesheet" href="{% static 'profil/css/emp.css' %}">
    <link rel="stylesheet" href="{% static 'profil/css/list_t.css' %}">
    <link rel="stylesheet" href="{% static 'profil/css/table.css' %}">
    <link rel="stylesheet" href="{% static 'profil/css/footer.css'%}">
    <script src="{% static 'profil/js/jquery-3.6.0.min.js' %}"></script>
</head>
<body class="bod">

    {% include 'profil/couche/sidebar.html' %}

    <section class="home-section emp">
        <div class="home-content">
            <i class="bx bx-menu"></i>
            <span class="text">Liste des terminaux</span>
        </div>
        <div class="content">
            <div class="table-container">
                <table class="list_t" id="list_t">
                    <thead>
                        <tr>
                            <th>Machine ip</th>
                            <th>Port</th>
                            <th>Statut</th> 
                            <th colspan="2">Action</th>
                            <th colspan="2">Download</th>   
                        </tr>
                    </thead>
                    <tbody>
                        {% for lecteur in zklect %}
                        <tr class="st">
                            <td>{{ lecteur.ip_adresse }}</td>
                            <td>{{ lecteur.n_port }}</td>
                            <td class="statut">
                                {% if forloop.counter0 < status_list|length %}
                                    {% if status_list.0 %}
                                        {% if status_list.0 %}
                                            <i class='bx bxs-circle' style="color: green;"></i>
                                        {% else %}
                                            <i class='bx bxs-circle' style="color: red;"></i>
                                        {% endif %}
                                    {% else %}
                                        <i class='bx bxs-circle' style="color: red;"></i>
                                    {% endif %}
                                {% else %}
                                    <i class='bx bxs-circle' style="color: red;"></i> <!-- Statut par défaut si aucune information -->
                                {% endif %}
                            </td>
                            <td><a href="{% url 'profil:modife_drive' lecteur.id %}"><i class="bx bxs-edit"></i></a></td>
                            <td><a href="{% url 'profil:delete_drive' lecteur.id %}"><i class="bx bxs-trash"></i></a></td>
                            <td><a href="{% url 'profil:add_users' lecteur.id %}"><i class="bx bxs-user-plus"></i></a></td>
                            <td><a href="{% url 'profil:get_log_data' lecteur.id %}"><i class="bx bxs-download"></i></a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                {% if messages %}
                    <ul>
                        {% for message in messages %}
                            <li>{{ message }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>
        </div>
    </section>
    {% include 'profil/couche/footer.html' %}
<script src="{% static 'profil/js/sidebar.js' %}"></script>
<script src="{% static 'profil/js/chk.js' %}"></script>
<script src="{% static 'profil/js/reload.js' %}"></script>
</body>
</html>

supertime/profil/templates/profil/liste_employe.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>liste</title>
    <link rel="stylesheet" href="{% static 'profil/boxicons-2.1.4/css/boxicons.min.css' %}" />
    <link rel="stylesheet" href="{% static 'profil/css/sidebar.css' %}">
    <link rel="stylesheet" href="{% static 'profil/css/emp.css' %}">
    <link rel="stylesheet" href="{% static 'profil/css/table.css' %}">
    <link rel="stylesheet" href="{% static 'profil/css/liste_u.css' %}">
    <link rel="stylesheet" href="{% static 'profil/css/footer.css'%}">
</head>
<body>

    {% include 'profil/couche/sidebar.html' %}

    <section class="home-section emp">
        <div class="home-content">
            <i class="bx bx-menu"></i>
            <span class="text">Liste des employés</span>
        </div>
        <form action="" method="GET" id="rech">
            <input type="search" name="rechercher" placeholder="rechercher">
            <button type="submit" id="search"><i class="bx bx-search"></i></button>
            <a class="link_name" href="{%url 'profil:liste_employe'%}"> <i class='bx bx-refresh' id="refresh"></i></a>
        </form>
            <table>
                <thead>
                    <tr>
                        <th><input type="checkbox" name="selected_employees" value="" class="checkall"></th>
                       
                        <th>Nom</th>
                        <th>Prénom</th>
                        <th>Email</th>
                        <th>Sexe</th>
                        <th>Poste</th>
                        <th>Salaire</th>
                        <th>Modifier</th>
                        
                    </tr>
                </thead>
                <form action="{% url 'profil:delete_employees' %}" method="POST">
                    {% csrf_token %}
                    {% for personnel in page_obj %}
                      <label>
              
                    <tr>
                        <td><input type="checkbox" name="selected_employees" value="{{ personnel.id }}" class="checkbox"></td>
                       
                        <td> <a href=" {% url 'profil:profil_employe' personnel.id %} "> {{ personnel.name }} </a></td>
                        <td>{{ personnel.first_name }}</td>
                        <td>{{ personnel.email }}</td>
                        <td>{{ personnel.gender }}</td>
                        <td>{{ personnel.poste }}</td>
                        <td>{{ personnel.salary }}</td>
                        <td><a href="{% url 'profil:modife_employe' personnel.id %}"><i class="bx bxs-edit"></i>  </a></td>
                        
                    </tr>
                             <!--  -->
                            
    </label>
    <br>
  {% endfor %}
  <div class="trash"><button type="submit" id="supp">Supprimer <i class="bx bxs-trash"></i></button></div>
</form>

            </table>


        

        <div class="fin">
            {% if page_obj.has_previous %}
              <div class="precedent"><a href="?page={{ page_obj.previous_page_number }}">Précédent</a></div>
            {% endif %}
            
           <div class="endpage"><span class="current-page">{{ page_obj.number }}</span></div>
            
            {% if page_obj.has_next %}
              <div class="suivant"><a href="?page={{ page_obj.next_page_number }}">Suivant</a></div>
            {% endif %}
        </div>

    </section>
    {% include 'profil/couche/footer.html' %}
<script src="{% static 'profil/js/sidebar.js' %}"></script>
<script src="{% static 'profil/js/chk.js' %}"></script>
</body>
</html>

supertime/profil/templates/profil/liste_poste.html
<!-- -->
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>liste</title>
    <link rel="stylesheet" href="{% static 'profil/boxicons-2.1.4/css/boxicons.min.css' %}" />
    <link rel="stylesheet" href="{% static 'profil/css/sidebar.css' %}">
    <link rel="stylesheet" href="{% static 'profil/css/table.css' %}">
    <link rel="stylesheet" href="{% static 'profil/css/liste_u.css' %}">
    <link rel="stylesheet" href="{% static 'profil/css/footer.css'%}">
</head>
<body>

    {% include 'profil/couche/sidebar.html' %}

    <section class="home-section emp">
        <div class="home-content">
            <i class="bx bx-menu"></i>
            <span class="text">Liste des postes</span>
        </div>
            <table>
                <thead>
                    <tr>
                        <th><input type="checkbox" name="" value="" class="checkall"></th>
                        <th>Alias poste</th>
                        <th>Nom poste</th>
                        <th>Heure d'arrivée</th>
                        <th>Heure de départ</th>
                        <th>Salaire</th>
                        <th colspan="2">Action</th>
                    </tr>
                </thead>
               {% for poste in postes %}
                    <tr>
            
                        <td><input type="checkbox" name="" value="{{ poste.id }}" class="checkbox"></td>
                        <td>{{poste.as_poste}}</td>
                        <td>{{poste.name_poste}}</td>
                        <td>{{poste.start_time}}</td>
                        <td>{{poste.end_time}}</td>
                        <td> {{poste.salary}} </td>
                        <td style="text-align: center;"><a href="{% url 'profil:modife_poste' poste.id %}"><i class="bx bxs-edit"></i></a></td>
                        <td style="text-align: center;"><a href="{% url 'profil:delete_poste' poste.id %}"><i class="bx bxs-trash"></i></a></td>
                       
                    </tr>
                  
                   {% endfor %}
            </table>

        
    </section>
    {% include 'profil/couche/footer.html' %}
<script src="{% static 'profil/js/sidebar.js' %}"></script>
<script src="{% static 'profil/js/chk.js' %}"></script>
</body>
</html>

supertime/profil/templates/profil/logs.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>liste</title>
    <link rel="stylesheet" href="{% static 'profil/boxicons-2.1.4/css/boxicons.min.css' %}" />
    <link rel="stylesheet" href="{% static 'profil/css/sidebar.css' %}">
    <link rel="stylesheet" href="{% static 'profil/css/emp.css' %}">
    <link rel="stylesheet" href="{% static 'profil/css/table.css' %}">
    <link rel="stylesheet" href="{% static 'profil/css/footer.css'%}">
</head>
<body>

    {% include 'profil/couche/sidebar.html' %}

    <section class="home-section emp">
        <div class="home-content">
            <i class="bx bx-menu"></i>
            <span class="text">Liste des logs</span>
        </div>
        <div id="tel">
            <a href="{% url 'profil:add_horaire' %}"><button id="search"><i class="bx bxs-download" style="color: white;">  Download</i></button></a>
        </div>
        <form action="" method="GET" id="rech">
            <!-- <input type="search" name="date_search" placeholder="date"> -->
            <input type="search" name="user_search" placeholder="employés">
            <button type="submit" id="search"><i class="bx bx-search"></i></button>
            <a class="link_name" href="{%url 'profil:logs'%}"> <i class='bx bx-refresh' id="refresh"></i></a>
        </form>
        <div class="content">
           <table>
            <thead>
                <tr>
                    <thead>
                    <tr>
                        <!-- <th>ID</th> -->
                        <th>Date</th>
                        <th>Status</th>
                        <th>Type Punch</th>
                        <th>User ID</th>
                        <th>Heure du check </th>
                       
                    </tr>
                </thead>
                <tbody>
                    {% for entry in page_obj %}
                    <tr>
                        <!-- <td>{{ entry.id_att }}</td> -->
                        <td>{{ entry.date }}</td>
                        <td>{{ entry.status }}</td>
                        <td>{{ entry.punch }}</td>
                        <td>{{ entry.personnel_a}}</td>
                        <td>{{ entry.heure_punch }}</td>
                        
                        
                    </tr>
                    {% endfor %}
            </tbody>
        </table>
        </div>

        

        <div class="fin">
            {% if page_obj.has_previous %}
              <div class="precedent"><a href="?page={{ page_obj.previous_page_number }}">Précédent</a></div>
            {% endif %}
            
           <div class="endpage"><span class="current-page">{{ page_obj.number }}</span></div>
            
            {% if page_obj.has_next %}
              <div class="suivant"><a href="?page={{ page_obj.next_page_number }}">Suivant</a></div>
            {% endif %}
        </div>

    </section>
    {% include 'profil/couche/footer.html' %}
<script src="{% static 'profil/js/sidebar.js' %}"></script>
<script src="{% static 'profil/js/chk.js' %}"></script>
</body>
</html>

supertime/profil/templates/profil/save_employe.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{%static 'profil/css/form.css'%}">
    <link rel="stylesheet" href="{% static 'profil/boxicons-2.1.4/css/boxicons.min.css' %}" />
    <link rel="stylesheet" href="{% static 'profil/css/sidebar.css' %}">
    <link rel="stylesheet" href="{% static 'profil/css/footer.css'%}">
</head>
      <body>

        {% include 'profil/couche/sidebar.html' %}
          
          <section class="home-section form">
              <div class="home-content">
                  <i class="bx bx-menu"></i>
                  <span class="text">Ajouter</span>
              </div>
                  <!-- MAIN -->
                  <div id="content">
                  <main>
                    

                    <div class="container">
                      <header>Formulaire d'ajout d'un employé</header>
                  
                      <form action="{% url 'profil:save_employe' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form first">
                          <div class="details personal">
                            <span class="title">Details de l'employé</span>
                  
                            <div class="fields">
                              <div class="input-field">
                                <label for="nom">Nom <span class="require">*</span> :</label>
                                <input type="text" placeholder="Entrer un nom:" name="nom" required>
                              </div>
                              <div class="input-field">
                                <label for="prenom">Prenom <span class="require">*</span> :</label>
                                <input type="text" placeholder="Entrer un prenom:" name="prenom" required>
                              </div>
                  
                              <div class="input-field">
                                <label for="email">Email <span class="require">*</span> :</label>
                                <input type="email" placeholder="Entrer un email" name="email" required>
                              </div>
                  
                              <div class="input-field">
                                <label for="gender">Genre:</label>
                                <select name="gender">
                                  <option disabled selected>------------</option>
                                  <option>Masculin</option>
                                  <option>Féminin</option>
                                </select>
                              </div>

                              <div class="input-field">
                                <label for="poste">Poste <span class="require">*</span> :</label>
                                
                                <select id="poste" name="poste" required>
                                    <option value="">----------------</option>
                                    {% for poste in postes %}
                                    <option value="{{ poste.id }}">{{ poste.name_poste }}</option>
                                  
                                    {% endfor %}
                                </select>
                              </div>
                  
                              <div class="input-field">
                                <label for="heure_fixe">Heures à effectuer(par mois) <span class="require">*</span> :</label>
                                <input type="number" name="heure_fixe" required>
                              </div>
                  
                              <div class="input-field">
                                <label for="salary">Salaire mensuel <span class="require">*</span> :</label>
                                <input type="number" name="salary" required>
                              </div>

                              <div class="input-field">
                                <label for="time_a">Heure d'arrivée <span class="require">*</span> :</label>
                                <input type="time" name="time_a" required>
                              </div>

                              <div class="input-field">
                                <label for="tolerance_time">Heure de tolérance <span class="require">*</span> :</label>
                                <input type="time" placeholder="Heure de tolérance" name="tolerance_time" required>
                              </div>

                              <div class="input-field">
                                <label for="time_s">Heure de sortie <span class="require">*</span> :</label>
                                <input type="time" name="time_s" required>
                              </div>

                              <div class="input-field">
                                <label for="user_id">Nom d'utilisateur <span class="require">*</span> :</label>
    
                                <select id="user" name="user_id" required>
                                    <option value="">----------------</option>
                                    {% for user in users %}
                                    <option value="{{ user.id }}">{{ user.username }}</option>
                                    {% endfor %}
                                </select>
                              </div>

                              <div class="input-field">
                                <label for="photo">Photo:</label>
                                <input type="file" name="photo" accept="image/*">
                              </div>

                            </div>
                          </div>
                  
                          <div class="details ID">
                            <div class="fields">
                            </div>
                  
                            <button type="submit" class="nextBtn">
                              <span class="btnText">Valider</span>
                            </button>
                          </div> 
                        </div>
                        <!-- </div>  end div second form -->
                      </form>
                    </div>
                  </main>
                  </div>
	              	<!-- MAIN -->
          </section>
          {% include 'profil/couche/footer.html' %}
      <script src="{% static 'profil/js/sidebar.js' %}"></script>
      <script>
        document.addEventListener('DOMContentLoaded', function() {
          var posteSelect = document.getElementById('poste');
          var salaryInput = document.querySelector('input[name="salary"]');

          posteSelect.addEventListener('change', function() {
              var selectedPosteId = this.value;
              if (selectedPosteId) {
                  // Envoyer une requête AJAX pour récupérer la valeur de somme associée à ce poste
                  var xhr = new XMLHttpRequest();
                  xhr.onreadystatechange = function() {
                      if (xhr.readyState === XMLHttpRequest.DONE) {
                          if (xhr.status === 200) {
                              // Mettre à jour la valeur du champ salaire avec la valeur récupérée
                              var response = JSON.parse(xhr.responseText);
                              salaryInput.value = response.somme;
                          } else {
                              console.error('Une erreur s\'est produite');
                          }
                      }
                  };
                  xhr.open('GET', '{% url "profil:get_somme_for_poste" %}?poste_id=' + selectedPosteId, true);
                  xhr.send();
              } else {
                  salaryInput.value = ''; // Effacer la valeur si aucun poste n'est sélectionné
              }
          });
      });
      </script>
      <script>
        document.addEventListener('DOMContentLoaded', function() {
          var posteSelect = document.getElementById('poste');
          var timeaInput = document.querySelector('input[name="time_a"]');

          posteSelect.addEventListener('change', function() {
              var selectedPosteId = this.value;
              if (selectedPosteId) {
                  // Envoyer une requête AJAX pour récupérer la valeur de somme associée à ce poste
                  var xhr = new XMLHttpRequest();
                  xhr.onreadystatechange = function() {
                      if (xhr.readyState === XMLHttpRequest.DONE) {
                          if (xhr.status === 200) {
                              // Mettre à jour la valeur du champ salaire avec la valeur récupérée
                              var response = JSON.parse(xhr.responseText);
                              timeaInput.value = response.start;
                          } else {
                              console.error('Une erreur s\'est produite');
                          }
                      }
                  };
                  xhr.open('GET', '{% url "profil:get_start" %}?poste_id=' + selectedPosteId, true);
                  xhr.send();
              } else {
                  timeaInput.value = ''; // Effacer la valeur si aucun poste n'est sélectionné
              }
          });
      });
      </script>
      <script>
        document.addEventListener('DOMContentLoaded', function() {
          var posteSelect = document.getElementById('poste');
          var timesInput = document.querySelector('input[name="time_s"]');

          posteSelect.addEventListener('change', function() {
              var selectedPosteId = this.value;
              if (selectedPosteId) {
                  // Envoyer une requête AJAX pour récupérer la valeur de somme associée à ce poste
                  var xhr = new XMLHttpRequest();
                  xhr.onreadystatechange = function() {
                      if (xhr.readyState === XMLHttpRequest.DONE) {
                          if (xhr.status === 200) {
                              // Mettre à jour la valeur du champ salaire avec la valeur récupérée
                              var response = JSON.parse(xhr.responseText);
                              timesInput.value = response.end;
                          } else {
                              console.error('Une erreur s\'est produite');
                          }
                      }
                  };
                  xhr.open('GET', '{% url "profil:get_end" %}?poste_id=' + selectedPosteId, true);
                  xhr.send();
              } else {
                  timesInput.value = ''; // Effacer la valeur si aucun poste n'est sélectionné
              }
          });
      });
      </script>
      <script>
        document.addEventListener('DOMContentLoaded', function() {
          var posteSelect = document.getElementById('poste');
          var timeWorkInput = document.querySelector('input[name="heure_fixe"]');

          posteSelect.addEventListener('change', function() {
              var selectedPosteId = this.value;
              if (selectedPosteId) {
                  // Envoyer une requête AJAX pour récupérer la valeur de somme associée à ce poste
                  var xhr = new XMLHttpRequest();
                  xhr.onreadystatechange = function() {
                      if (xhr.readyState === XMLHttpRequest.DONE) {
                          if (xhr.status === 200) {
                              // Mettre à jour la valeur du champ salaire avec la valeur récupérée
                              var response = JSON.parse(xhr.responseText);
                              timeWorkInput.value = response.time_work;
                          } else {
                              console.error('Une erreur s\'est produite');
                          }
                      }
                  };
                  xhr.open('GET', '{% url "profil:get_time_work" %}?poste_id=' + selectedPosteId, true);
                  xhr.send();
              } else {
                  timeWorkInput.value = ''; // Effacer la valeur si aucun poste n'est sélectionné
              }
          });
      });
      </script>
      <script>
        document.addEventListener('DOMContentLoaded', function() {
          var posteSelect = document.getElementById('poste');
          var toleranceTimeInput = document.querySelector('input[name="tolerance_time"]');

          posteSelect.addEventListener('change', function() {
              var selectedPosteId = this.value;
              if (selectedPosteId) {
                  // Envoyer une requête AJAX pour récupérer la valeur de somme associée à ce poste
                  var xhr = new XMLHttpRequest();
                  xhr.onreadystatechange = function() {
                      if (xhr.readyState === XMLHttpRequest.DONE) {
                          if (xhr.status === 200) {
                              // Mettre à jour la valeur du champ salaire avec la valeur récupérée
                              var response = JSON.parse(xhr.responseText);
                              toleranceTimeInput.value = response.tolerance_time;
                          } else {
                              console.error('Une erreur s\'est produite');
                          }
                      }
                  };
                  xhr.open('GET', '{% url "profil:get_tolerance_time" %}?poste_id=' + selectedPosteId, true);
                  xhr.send();
              } else {
                  toleranceTimeInput.value = ''; // Effacer la valeur si aucun poste n'est sélectionné
              }
          });
      });
      </script>
  </body>
  </html>