supertime/profil/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name = 'profil'

urlpatterns=[
    path('',views.first_time_user,name='register'),
    path('index/',views.index, name='index'),
    path('dashboad/',views.dashboard,name='dashboad'),
    path('add/poste/', views.add_poste , name='save_poste'),
    path('add/personnel/', views.add_personnel, name='save_employe'),
    # path('details/', views.detail_register, name='details_user'),
    path('personnel/list/', views.personnel_list , name='liste_employe'),
    # path('Ajout horaire/', views.part3, name='part3'),
    path('attendance/',views.attendance,name='attendance'),
    path('dowloands/log/lecteur?<int:lecteur_id>/',views.get_log_data,name='get_log_data'),
    path('dowloands/user/lecteur?<int:lecteur_id>/',views.add_users,name='add_users'),
    path('user/list/',views.user_list,name="liste_user"),
    path('logs/data/',views.raw_data,name='logs'),
    path('get_somme_for_poste/', views.get_somme_for_poste, name='get_somme_for_poste'),
    path('get_start/', views.get_start, name='get_start'),
    path('get_end/', views.get_end, name='get_end'),
    path('get_time_work/', views.get_time_work, name='get_time_work'),
    path('get_tolerance_time/', views.get_tolerance_time, name = 'get_tolerance_time'),
    path('dowloands/attendance/', views.get_attendance_data, name = 'add_horaire'),
    path('historique/',views.historique,name='historique'),
    path('add/lecteur/',views.add_drive, name='add_drive'),
    path('help/',views.help,name='help'),
    path('edit/poste/<int:poste_id>/', views.edit_poste, name='modife_poste'),
    path('edit/personnel/personnel?<int:personnel_id>/',views.edit_personnel,name='modife_employe'),
    path('edit/attendances/attendance?<int:Horaire_id>/',views.edit_attendance,name='modife_attendance'),
    path('profil/employe?<int:Personnel_id>/',views.personnel_profil,name='profil_employe'),
    path('delete-employe/employé?<int:Personnel_id>/',views.delete_personnel,name='delete_personnel'),
    path('delete-poste/poste?<int:Poste_id>/',views.delete_poste,name='delete_poste'),
    path('ternimal/list/', views.terminal_list, name = 'liste_drive'),
    path('profil/user/',views.user_profil, name = 'profil_user'),
    path('poste/', views.poste_list, name='liste_poste'),
    path('Fiche/<int:Personnel_id>/', views.personnel_salary, name='salary'),
    path('delete-lecteur/id=<int:lecteur_id>/',views.delete_drive,name='delete_drive'),
    path('edit/lecteur/id=<int:lecteur_id>/',views.edit_drive,name='modife_drive'),
    path('delete-employe/',views.delete_employees,name='delete_employees'),
    path('dowloands/log-alls/',views.get_all_log_data,name='get_all_log_data'),
      
]

supertime/profil/templates/profil/couche/footer.html
{% load static %}

<footer class="footer">
    <div class="footer-container">
        <div class="row">
            <div class="footer-col">
                <a href="https://innovations-groups.com"><img src="{% static 'profil/ressources/logo-innovation-removebg-140x111.png' %}" alt=""></a>
            </div>
            <div class="footer-col">
                <h4>Entreprise</h4>
                <ul>
                    <li><a href="https://innovations-groups.com/a-propos-de-nous/" target="_blank">A propos</a></li>
                    <li><a href="https://innovations-groups.com/services/" target="_blank">Nos services</a></li>
                    <li><a href="https://inno-entreprise.com/shop" target="_blank">Shop</a></li>
                    <li><a href="https://innovations-groups.com/contact/" target="_blank">Contacts</a></li>
                </ul>
            </div>
            <div class="footer-col">
                <h4>follow us</h4>
                <div class="social-links">
                    <a href="https://wa.me/+15813491779" target="_blank"><i class='bx bxl-whatsapp' ></i></a>
                    <a href="https://www.facebook.com/innovationsarlpro/" target="_blank"><i class="bx bxl-facebook"></i></a>
                    <a href="https://www.linkedin.com/company/innovations-groups/" target="_blank"><i class='bx bxl-linkedin'></i></a>
                </div>
            </div>
            <p style="text-align: center;">Copyright © 2024 Innovations Groups | Fait par Innovations Groups</p>
        </div>
    </div>
</footer>

supertime/profil/templates/profil/couche/sidebar.html
{% load static %}

<div class="sidebar">
    <div class="logo-details">
        <i class="bx bx-atom"></i>
        <span class="logo_name">Inno Time</span>
    </div>
    <ul class="nav-links">
                <li>
                    <a href="{%url 'profil:dashboad'%}">
                        <i class="bx bx-grid-alt"></i>
                        <span class="link_name">Dashboard</span>
                    </a>
                    <ul class="sub-menu blank">
                        <li><a class="link_name" href="{%url 'profil:dashboad'%}">Dashboard</a></li>
                    </ul>
                </li>
                <li>
                    <div class="icon-link">
                        <a href="{%url 'profil:liste_employe'%}">
                            <i class="bx bxs-user-detail"></i>
                            <span class="link_name">Employés</span>
                        </a>
                            <i class="bx bxs-chevron-down arrow arrow"></i>
                    </div>
                    <ul class="sub-menu">
                        <li><a class="link_name" href="{%url 'profil:liste_employe'%}">Employés</a></li>
                        <li><a href="{%url 'profil:liste_employe'%}">Liste</a></li>
                        <li><a href="{%url 'profil:save_employe'%}">Ajouter</a></li>
                    </ul>
                </li>
                <li>
                    <div class="icon-link">
                        <a href="{%url 'profil:liste_poste'%}">
                            <i class='bx bxs-briefcase'></i>
                            <span class="link_name">Postes</span>
                        </a>
                            <i class="bx bxs-chevron-down arrow arrow"></i>
                    </div>
                    <ul class="sub-menu">
                        <li><a class="link_name" href="{%url 'profil:liste_poste'%}">Postes</a></li>
                        <li><a href="{%url 'profil:liste_poste'%}">Liste</a></li>
                        <li><a href="{%url 'profil:save_poste'%}">Ajouter</a></li>
                    </ul>
                </li>
                <li>
                    <div class="icon-link">
                        <a href="{%url 'profil:attendance'%}">
                            <i class="bx bxs-time"></i>
                            <span class="link_name">Présences</span></a>
                            <i class="bx bxs-chevron-down arrow"></i>
                    </div>
                    <ul class="sub-menu">
                        <li><a class="link_name" href="{%url 'profil:attendance'%}">Présences</a></li>
                        <li><a href="{%url 'profil:attendance'%}">Présences</a></li>
                        <li><a href="{%url 'profil:historique'%}">Historique</a></li>
                    </ul>
                </li>
                <li>
                    <div class="icon-link">
                        <a href="{%url 'profil:liste_user'%}">
                            <i class="bx bxs-user"></i>
                            <span class="link_name">Utilisateurs</span>
                        </a>
                            <i class="bx bxs-chevron-down arrow arrow"></i>
                    </div>
                    <ul class="sub-menu">
                        <li><a class="link_name" href="{%url 'profil:liste_user'%}">Utilisateurs</a></li>
                        <li><a href="{%url 'profil:liste_user'%}">Liste</a></li>
                        <li><a href="{%url 'accounts:register'%}">Ajouter</a></li>
                    </ul>
                </li>
                <li>
                    <div class="icon-link">
                        <a href="{%url 'profil:liste_drive'%}">
                            <i class="bx bx-laptop"></i>
                            <span class="link_name">Terminal</span>
                        </a>
                            <i class="bx bxs-chevron-down arrow arrow"></i>
                    </div>
                    <ul class="sub-menu">
                        <li><a class="link_name" href="{%url 'profil:liste_drive' %}">Terminal</a></li>
                        <li><a href="{%url 'profil:liste_drive'%}">Liste</a></li>
                        <li><a href="{%url 'profil:add_drive'%}">Ajouter</a></li>
                        <li><a href="{%url 'profil:logs'%}">Logs</a></li>
                   
                    </ul>
                </li>
                {% comment %}
                <li>
                    <a href="{%url 'profil:attendance'%}">
                        <i class='bx bx-rss'></i>
                        <span class="link_name">Logs</span>
                    </a>
                    <ul class="sub-menu blank">
                        <li><a class="link_name" href="{%url 'profil:attendance'%}">Logs</a></li>
                    </ul>
                </li>
                {% endcomment %}
                <li>
                    <a href="{%url 'profil:help'%}">
                        <i class='bx bxs-help-circle' ></i>
                        <span class="link_name">Aide</span>
                    </a>
                    <ul class="sub-menu blank">
                        <li><a class="link_name" href="{%url 'profil:help'%}">Aide</a></li>
                    </ul>
                </li>
                <li>
            <div class="profile-details">
                <div class="profile-content">
                    {% if user.personnel.get_self.photo %}
                    <a href="{% url 'profil:profil_user' %}"><img src="{{ user.personnel.get_self.photo.url }}" alt="profile"></a>
                    {% else %}
                    <a href="{% url 'profil:profil_user' %}"><img src="{% static 'profil/ressources/user-3331256_1280.png' %}" alt="profile"></a>
                    {% endif %}
                </div>
                
                <div class="name-job">
                    <div class="profile_name">{{ user.username }}</div>
                    <div class="job">{{ user.personnel.get_self.poste }}</div>
                </div>
                <a href="{% url 'accounts:logout' %}">
                <i class="bx bx-log-out"></i>
                </a>
            </div>
        </li>
    </ul>
</div>