setup/Inno Time/_internal/supertime/profil/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name = 'profil'

urlpatterns=[
    path('',views.first_time_user,name='register'),
    path('index/',views.index, name='index'),
    path('Acceuil/',views.acceuil,name='acceuil'),
    path('Ajout poste/', views.part1, name='part1'),
    path('Ajout personnel/', views.part2, name='part2'),
    # path('details/', views.detail_register, name='details_user'),
    path('liste_e', views.liste_e, name='liste_e'),
    # path('Ajout horaire/', views.part3, name='part3'),
    path('attendance/',views.attendance,name='attendance'),
    #-------------------------------------------#
    path('add_att/id=<int:lecteur_id>/',views.get_attendance_data,name='add_attendance'),
    path('add_user/id=<int:lecteur_id>/',views.add_users,name='add_users'),
    path('liste_u/',views.liste_u,name="liste"),
    path('data/',views.data,name='data'),
    path('data_zk/',views.data_brute,name='a_valide'),
    # path('get_save/',views.filter_and_save_attendance ,name='filter_and_save_attendance'),
    path('get_somme_for_poste/', views.get_somme_for_poste, name='get_somme_for_poste'),
    path('get_start/', views.get_start, name='get_start'),
    path('get_end/', views.get_end, name='get_end'),
    path('get_time_work/', views.get_time_work, name='get_time_work'),
    path('get_tolerance_time/', views.get_tolerance_time, name = 'get_tolerance_time'),
    # path('data_get/',views.save_attendance ,name='attendance_saved.html'),
    path('valide/', views.valide, name='valide'),
    path('add_horaire/', views.horaire, name = 'add_horaire'),
    #-------------------------------------------#
    path('historique/',views.historique,name='historique'),
    path('machine/',views.machine, name='machine'),
    path('help/',views.help,name='help'),
    # path('modifie_infor_poste/<int:Poste_id>/',views.edit_Poste,name='partm1'),
    path('partm1/<int:poste_id>/', views.partm1, name='partm1'),
    path('modifie_infor_personnel/<int:personnel_id>/',views.part2m,name='partm2'),
    path('modifie_infor_horaire/<int:Horaire_id>/',views.edit_Horaire,name='partm3'),
    path('profile_employé/id=<int:Personnel_id>/',views.profil_e,name='profil_e'),
    path('delete employé/id=<int:Personnel_id>/',views.del_user,name='delt_user'),
    path('delete poste/id=<int:Poste_id>/',views.del_poste,name='delt_poste'),
    path('liste_t', views.liste_t, name = 'liste_t'),
    path('profil_u/',views.profil_u, name = 'profil_user'),
    path('poste/', views.post, name='poste'),
  
    path('Fiche/<int:Personnel_id>/', views.personnel_salary, name='salaire'),
  path('delete_lecteur/id=<int:lecteur_id>/',views.del_lecteur,name='del_lecteur'),
    
    path('edit_lecteur/id=<int:lecteur_id>/',views.edit_lecteur,name='edit_lecteur'),
    #path('data/id=<int:lecteur_id>/', views.data, name='data'),
    path('poste/', views.post, name='poste'),
    path('delete_employees',views.delete_employees,name='delete_employees')
  

    # path('ajout_profil/',views.add_Profil,name='add_Profil'),
]

setup/Inno Time/_internal/supertime/profil/forms.py
from django import forms
from .models import Poste,Horaire,Zklecteur,Personnel
from datetime import time,date

# formulaire du poste
class Part1Form(forms.ModelForm):
    class Meta:
        model = Poste
        fields = ['as_poste','nom_poste','somme','heure_debut','heure_fin']
  
# formulaire du personnel
class Part2Form(forms.ModelForm):
     class Meta:
        model = Personnel
        fields = ['name','prenom','email','gender','poste','heure_fixe','salary','user']
        labels = {'name':'Nom','prenom':'Prénom','email':'Email','salary':'Plus value',
                  'heure_fixe':'Heure à effectuer','gender':'Genre','poste':'Poste','user':'User'}

# formulaire des horaires
class Part3Form(forms.ModelForm):
    
    class Meta:
        
        model = Horaire
        fields = ['date_d','arrival_time','departure_time','personnel','status','punch','id_att']
#         initial = {'date_d': date.today()}

       

class ZKTecoForm(forms.ModelForm):
    # ip_address = forms.CharField(label='Adresse IP')
    # port_number = forms.IntegerField(label='Numéro de port')
    class Meta:
        model=Zklecteur
        fields = ['ip_adresse','n_port']

setup/Inno Time/_internal/supertime/profil/views.py
from django.shortcuts import render, get_list_or_404,redirect
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from .models import Horaire,Poste, Salaire,Zklecteur,Personnel,Attendance
from .forms import Part1Form, Part2Form,Part3Form,ZKTecoForm
from django.contrib.auth.models import User
from datetime import datetime, timedelta, timezone,date,time
from django.core.paginator import Paginator
from django.db.models import Count, Q
import subprocess
from zk import ZK, const
import threading
from threading import Thread
import os
import sys
import asyncio
from django.utils import timezone
import calendar
from django.db.models import Min, Max
from dateutil.relativedelta import relativedelta



CWD = os.path.dirname(os.path.realpath(__file__))
ROOT_DIR = os.path.dirname(CWD)
sys.path.append(ROOT_DIR)




   
# # @login_required(login_url="/account/login_admin/")
# @login_required(login_url="/account/login_admin/")
# def liste_t(request):
#     lecteurs = Zklecteur.objects.all()
#     status_list = []
#     messages = []

#     for lecteur in lecteurs:
#         zk = ZK(lecteur.ip_adresse, lecteur.n_port, timeout=1)
#         conn = None
#         status = False

#         try:
#             conn = zk.connect()
#             status = conn.is_connect
#             status_list.append(status)
#         except Exception as e:
#             messages.append("Erreur de connexion avec le lecteur {}: {}".format(lecteur.id, e))
#         finally:
#             if conn is not None and conn.is_connect:
#                 conn.disconnect()

#     return render(request, 'profil/liste_t.html', {'zklect': lecteurs, 'status_list': status_list, 'messages': messages})


@login_required(login_url="/account/login_admin/")
def liste_t(request):
    lecteurs = Zklecteur.objects.all()
    status_list = []
    messages = []

    def check_status(lecteur):
        zk = ZK(lecteur.ip_adresse, lecteur.n_port, timeout=1)
        conn = None
        status = False

        try:
            conn = zk.connect()
            status = conn.is_connect
            status_list.append(status)
        except Exception as e:
            messages.append("Erreur de connexion avec le lecteur {}: {}".format(lecteur.id, e))
        finally:
            if conn is not None and conn.is_connect:
                conn.disconnect()

    def check_all_statuses():
        threads = []
        for lecteur in lecteurs:
            thread = threading.Thread(target=check_status, args=(lecteur,))
            threads.append(thread)
            thread.start()

        for thread in threads:
            thread.join()

    check_all_statuses()

    return render(request, 'profil/liste_t.html', {'zklect': lecteurs, 'status_list': status_list, 'messages': messages})


#-------------------------------------------------------------------------------------------------------------#
@login_required(login_url="/account/login_admin/")
def add_users(request, lecteur_id):
    statut=None
    lecteurs = Zklecteur.objects.get(pk=lecteur_id)
    conn = None
    zk = ZK(lecteurs.ip_adresse, port=lecteurs.n_port, timeout=2)
    try:
        conn = zk.connect()
        print('Disabling device ...')
        conn.disable_device()
        print('--- Get User ---')
        users = conn.get_users()
        
        for user in users:
            zkteco_username = user.name
            zkteco_user_id = user.user_id
            pw = user.password
            print(zkteco_user_id, zkteco_username, pw)
            
            try:
                django_user = User.objects.get(username=zkteco_user_id)
                # Si l'utilisateur existe, mettez à jour ses informations
                django_user.zkteco_user_id = zkteco_user_id
                django_user.save()
                pass
            except User.DoesNotExist:
                # Si l'utilisateur n'existe pas, créez un nouvel utilisateur Django
                django_user = User.objects.create_user(username=zkteco_user_id,password=pw)
                django_user.zkteco_user_id = zkteco_user_id
                django_user.save()
                if user.privilege == const.USER_ADMIN:  # Assurez-vous que votre appareil ZKTeco fournit cette information
                    django_user.is_superuser = True
                    django_user.save()
               
    
            
            # Vérifier le statut de l'utilisateur dans le lecteur
            
                
        print('Enabling device ...')
        conn.enable_device()
            
    except Exception as e:
        print("Process terminate : {}".format(e))
    finally:
        if conn is not None and conn.is_connect:
            conn.disconnect()
            
    return render(request, "profil/valide.html", {'statut':statut})

# def add_users(request, lecteur_id):
    # statut = None
    # lecteurs = Zklecteur.objects.get(pk=lecteur_id)
    # conn = None
    # zk = ZK(lecteurs.ip_adresse, port=lecteurs.n_port, timeout=2)
    # try:
    #     conn = zk.connect()
    #     print('Disabling device ...')
    #     conn.disable_device()
    #     print('--- Get Users ---')
    #     users = conn.get_all_users()
        
    #     for user in users:
    #         zkteco_username = user.name
    #         zkteco_user_id = user.uid
    #         pw = user.password
    #         print(zkteco_user_id, zkteco_username, pw)
            
    #         try:
    #             django_user = User.objects.get(username=zkteco_username)
    #             # Si l'utilisateur existe, mettez à jour ses informations
    #             django_user.zkteco_user_id = zkteco_user_id
    #             django_user.save()
    #         except User.DoesNotExist:
    #             # Si l'utilisateur n'existe pas, créez un nouvel utilisateur Django
    #             django_user = User.objects.create_user(username=zkteco_username, password=pw)
    #             django_user.zkteco_user_id = zkteco_user_id
    #             django_user.save()
    #             # Enregistrer l'utilisateur en tant que superutilisateur si nécessaire
    #             if user.privilege == const.USER_ADMIN:  # Assurez-vous que votre appareil ZKTeco fournit cette information
    #                 django_user.is_superuser = True
    #                 django_user.save()
                
    #         # Vérifier le statut de l'utilisateur dans la base de données Django
    #         if User.objects.filter(username=zkteco_username).exists():
    #             if conn.get_user(uid=zkteco_user_id):
    #                 statut = "Actif"
    #             else:
    #                 statut = "Inactif"
            
    #     print('Enabling device ...')
    #     conn.enable_device()
            
    # except Exception as e:
    #     print("Process terminate : {}".format(e))
    # finally:
    #     if conn is not None and conn.is_connect:
    #         conn.disconnect()
            
    # return render(request, "profil/valide.html", {'statut': statut})

@login_required(login_url="/account/login_admin/")
def valide(request):
    statut = request.GET.get('statut', None)
    return render(request, "profil/valide.html", {'statut':statut})


@login_required(login_url="/account/login_admin/")
def data(request):
    attendance=Attendance.objects.all()
    if request.method == "GET":
        
        date_search=request.GET.get('rechercher')
        personnel_search=request.GET.get('rechercher')
        if personnel_search is not None or date_search:
            
            attendance_list = Attendance.objects.filter(date__startswith=date_search,personnel_a=personnel_search)
    


    paginator = Paginator(attendance_list, 10)  # Paginer la liste avec 10 employés par page
    
    page_number = request.GET.get('page')  # Récupérer le numéro de page depuis les paramètres GET
    page_obj = paginator.get_page(page_number)  # Obtenir l'objet Page pour la page demandée
    context = {'page_obj': page_obj,
               
               
               }
    return render(request,'profil/data.html',context)

@login_required(login_url="/account/login_admin/")
def data_brute(request):
    attendance_list=Attendance.objects.order_by('-date','-heure_punch')
    if request.method == "GET":
        
        # date_search=request.GET.get('date_search')
        personnel_search=request.GET.get('user_search')
        if personnel_search is not None: 
            
            attendance_list = Attendance.objects.filter(personnel_a=personnel_search)
          
    paginator = Paginator(attendance_list, 10)  # Paginer la liste avec 10 employés par page
    
    page_number = request.GET.get('page')  # Récupérer le numéro de page depuis les paramètres GET
    page_obj = paginator.get_page(page_number)  # Obtenir l'objet Page pour la page demandée
    context = {'page_obj': page_obj,
               
               
               }
    return render(request,'profil/a_valide.html',context)



@login_required(login_url="/account/login_admin/")
def liste_u(request):
    users=User.objects.all()
    return render(request,'profil/liste.html',{"users":users})



@login_required(login_url="/account/login_admin/")
def get_attendance_data(request, lecteur_id):
    lecteurs = Zklecteur.objects.get(pk=lecteur_id)
    zk = ZK(lecteurs.ip_adresse, lecteurs.n_port, timeout=2)
    try:
        conn = zk.connect()
        print('Disabling device ...')
        conn.disable_device()
        print('--- Get User ---')
        attendance = conn.get_attendance()
        print(type(attendance))
        print(attendance)

        for user in attendance:
            id_a = user.uid
            check_heure = user.timestamp
            status_a = user.status
            user_id = user.user_id
            punch_a = user.punch
            try:
                try:
                    # Tentative de récupération de l'objet Attendance avec l'identifiant spécifié
                    django_user = Attendance.objects.get(id_att=id_a)
                    pass

setup/Inno Time/_internal/supertime/profil/templates/profil/couche/sidebar.html
{% load static %}

<div class="sidebar">
    <div class="logo-details">
        <i class="bx bx-atom"></i>
        <span class="logo_name">Inno Time</span>
    </div>
    <ul class="nav-links">
                <li>
                    <a href="{%url 'profil:acceuil'%}">
                        <i class="bx bx-grid-alt"></i>
                        <span class="link_name">Dashboard</span>
                    </a>
                    <ul class="sub-menu blank">
                        <li><a class="link_name" href="{%url 'profil:acceuil'%}">Dashboard</a></li>
                    </ul>
                </li>
                <li>
                    <div class="icon-link">
                        <a href="{%url 'profil:liste_e'%}">
                            <i class="bx bxs-user-detail"></i>
                            <span class="link_name">Employés</span>
                        </a>
                            <i class="bx bxs-chevron-down arrow arrow"></i>
                    </div>
                    <ul class="sub-menu">
                        <li><a class="link_name" href="{%url 'profil:liste_e'%}">Employés</a></li>
                        <li><a href="{%url 'profil:liste_e'%}">Liste</a></li>
                        <li><a href="{%url 'profil:part2'%}">Ajouter</a></li>
                    </ul>
                </li>
                <li>
                    <div class="icon-link">
                        <a href="{%url 'profil:poste'%}">
                            <i class='bx bxs-briefcase'></i>
                            <span class="link_name">Postes</span>
                        </a>
                            <i class="bx bxs-chevron-down arrow arrow"></i>
                    </div>
                    <ul class="sub-menu">
                        <li><a class="link_name" href="{%url 'profil:poste'%}">Postes</a></li>
                        <li><a href="{%url 'profil:poste'%}">Liste</a></li>
                        <li><a href="{%url 'profil:part1'%}">Ajouter</a></li>
                    </ul>
                </li>
                <li>
                    <div class="icon-link">
                        <a href="{%url 'profil:attendance'%}">
                            <i class="bx bxs-time"></i>
                            <span class="link_name">Présences</span></a>
                            <i class="bx bxs-chevron-down arrow"></i>
                    </div>
                    <ul class="sub-menu">
                        <li><a class="link_name" href="{%url 'profil:attendance'%}">Présences</a></li>
                        <li><a href="{%url 'profil:attendance'%}">Présences</a></li>
                        <li><a href="{%url 'profil:historique'%}">Historique</a></li>
                    </ul>
                </li>
                <li>
                    <div class="icon-link">
                        <a href="{%url 'profil:liste'%}">
                            <i class="bx bxs-user"></i>
                            <span class="link_name">Utilisateurs</span>
                        </a>
                            <i class="bx bxs-chevron-down arrow arrow"></i>
                    </div>
                    <ul class="sub-menu">
                        <li><a class="link_name" href="{%url 'profil:liste'%}">Utilisateurs</a></li>
                        <li><a href="{%url 'profil:liste'%}">Liste</a></li>
                        <li><a href="{%url 'accounts:register'%}">Ajouter</a></li>
                    </ul>
                </li>
                <li>
                    <div class="icon-link">
                        <a href="{%url 'profil:liste_t'%}">
                            <i class="bx bx-laptop"></i>
                            <span class="link_name">Terminal</span>
                        </a>
                            <i class="bx bxs-chevron-down arrow arrow"></i>
                    </div>
                    <ul class="sub-menu">
                        <li><a class="link_name" href="{%url 'profil:liste_t' %}">Terminal</a></li>
                        <li><a href="{%url 'profil:liste_t'%}">Liste</a></li>
                        <li><a href="{%url 'profil:machine'%}">Ajouter</a></li>
                        <li><a href="{%url 'profil:a_valide'%}">Data</a></li>
                   
                    </ul>
                </li>
                {% comment %}
                <li>
                    <a href="{%url 'profil:attendance'%}">
                        <i class='bx bx-rss'></i>
                        <span class="link_name">Logs</span>
                    </a>
                    <ul class="sub-menu blank">
                        <li><a class="link_name" href="{%url 'profil:attendance'%}">Data</a></li>
                    </ul>
                </li>
                {% endcomment %}
                <li>
                    <a href="{%url 'profil:help'%}">
                        <i class='bx bxs-help-circle' ></i>
                        <span class="link_name">Aide</span>
                    </a>
                    <ul class="sub-menu blank">
                        <li><a class="link_name" href="{%url 'profil:help'%}">Aide</a></li>
                    </ul>
                </li>
                <li>
            <div class="profile-details">
                <div class="profile-content">
                    {% if user.personnel.get_self.photo %}
                    <a href="{% url 'profil:profil_user' %}"><img src="{{ user.personnel.get_self.photo.url }}" alt="profile"></a>
                    {% else %}
                    <a href="{% url 'profil:profil_user' %}"><img src="{% static 'profil/ressources/user-3331256_1280.png' %}" alt="profile"></a>
                    {% endif %}
                </div>
                
                <div class="name-job">
                    <div class="profile_name">{{ user.username }}</div>
                    <div class="job">{{ user.personnel.get_self.poste }}</div>
                </div>
                <a href="{% url 'accounts:logout' %}">
                <i class="bx bx-log-out"></i>
                </a>
            </div>
        </li>
    </ul>
</div>